(function () {
    "use strict";

    const CART_KEY = "bsscosGlobalCartV1";
    const LANGUAGE_KEY = "bsscosLanguage";
    let cart = readJSON(CART_KEY, []);
    let language = localStorage.getItem(LANGUAGE_KEY) === "en" ? "en" : "ms";
    let cartElements = null;
    let translating = false;

    const translations = {
        "Selamat Datang ke B-SSCOS": "Welcome to B-SSCOS",
        "Cara Sistem Berfungsi": "How the System Works",
        "Visi, Misi & Objektif": "Vision, Mission & Objectives",
        "Visi": "Vision",
        "Misi": "Mission",
        "Objektif": "Objective",
        "Pautan Pantas": "Quick Links",
        "Soalan Lazim": "Frequently Asked Questions",
        "Set Permulaan": "Starter Set",
        "Tingkatan 1": "Form 1",
        "Tingkatan 2": "Form 2",
        "Tingkatan 3": "Form 3",
        "Tingkatan 4": "Form 4",
        "Tingkatan 5": "Form 5",
        "Berita & Pengumuman": "News & Announcements",
        "Ulasan & Kata-Kata": "Reviews & Testimonials",
        "Hubungan & Platform Dalam Talian": "Contact & Online Platforms",
        "Tempahan Set Permulaan Sekolah": "School Starter Set Order",
        "Pilih Pelbagai Tingkatan Dalam Satu Pesanan": "Select Multiple Forms in One Order",
        "Tiada Tingkatan Dipilih": "No Form Selected",
        "Sejarah Pesanan": "Order History",
        "Sila Log Masuk Terlebih Dahulu": "Please Login First",
        "Muat Naik Resit Pembayaran": "Upload Payment Receipt",
        "Ketersediaan Stok": "Stock Availability",
        "Semakan Stok Yang Lebih Pantas": "Faster Stock Checking",
        "Soalan Lazim & Aduan": "FAQ & Feedback",
        "Pusat Bantuan B-SSCOS": "B-SSCOS Help Centre",
        "Hantar Aduan": "Submit Feedback",
        "Maklum Balas Melalui Gmail": "Feedback via Gmail",
        "Perlukan Bantuan Segera?": "Need Immediate Help?",
        "Log Masuk & Daftar": "Login & Register",
        "Akses Akaun B-SSCOS": "Access Your B-SSCOS Account",
        "Daftar Akaun Baharu": "Register a New Account",
        "Nama Pengguna": "User Name",
        "Email": "Email",
        "Laman Utama": "Home",
        "Pesanan": "Order",
        "Stok": "Stock",
        "Soalan Lazim & Aduan": "FAQ & Feedback",
        "Log Masuk / Daftar": "Login / Register",
        "Halaman Pesanan": "Order Page",
        "Semak Stok": "Check Stock",
        "Mula Membuat Pesanan": "Start Ordering",
        "Pilih Tingkatan": "Select Form",
        "Ringkasan Pesanan": "Order Summary",
        "Jumlah Keseluruhan": "Grand Total",
        "Pesan & Bayar": "Order & Pay",
        "Tiada tingkatan dipilih.": "No form selected.",
        "Pilih Saiz": "Select Size",
        "Kuantiti": "Quantity",
        "Harga Seunit": "Unit Price",
        "Jumlah": "Total",
        "Pilih": "Select",
        "Perkara": "Item",
        "Saiz": "Size",
        "Wajib": "Required",
        "Add-on": "Add-on",
        "Buang": "Remove",
        "Panduan Saiz": "Size Guide",
        "Semua Barangan Koperasi": "All Cooperative Items",
        "Nama Item": "Item Name",
        "Baki Stok": "Stock Balance",
        "Status": "Status",
        "Sedia Ditempah": "Ready to Order",
        "Pilihan Saiz Tersedia": "Sizes Available",
        "Hampir Habis": "Almost Sold Out",
        "Kehabisan Stok": "Out of Stock",
        "Lupa kata laluan?": "Forgot password?",
        "Kata Laluan": "Password",
        "Sahkan Kata Laluan": "Confirm Password",
        "Daftar Akaun": "Register Account",
        "Log Masuk": "Login",
        "Log Keluar": "Logout",
        "Batal": "Cancel",
        "Simpan Kata Laluan": "Save Password",
        "Tetapkan Semula Kata Laluan": "Reset Password",
        "E-mel Berdaftar": "Registered Email",
        "Kata Laluan Baharu": "New Password",
        "Sahkan Kata Laluan Baharu": "Confirm New Password",
        "Bantuan": "Help",
        "Aduan": "Feedback",
        "Akaun Pengguna": "User Account",
        "Hubungi WhatsApp": "Contact via WhatsApp",
        "Waktu Operasi": "Operating Hours",
        "Telefon": "Telephone",
        "Lokasi Kami": "Our Location",
        "Dapatkan Arah": "Get Directions",
        "Cara pesan": "How to order",
        "Semak stok": "Check stock",
        "Barang / tukar saiz": "Items / change size"
    };

    const placeholderTranslations = {
        "Taip soalan anda...": "Type your question...",
        "Masukkan e-mel anda": "Enter your email",
        "Masukkan kata laluan anda": "Enter your password",
        "Cipta kata laluan": "Create a password",
        "Sahkan kata laluan anda": "Confirm your password",
        "Masukkan nama pengguna": "Enter your user name",
        "Cari soalan lazim...": "Search frequently asked questions..."
    };

    /* Complete page copy. These entries cover all five static pages as well as
       the text generated by the order, login and history interfaces. */
    Object.assign(translations, {
        "B-SSCOS - Laman Utama": "B-SSCOS - Home",
        "B-SSCOS - Pesanan": "B-SSCOS - Order",
        "B-SSCOS - Stok": "B-SSCOS - Stock",
        "B-SSCOS - Soalan Lazim & Aduan": "B-SSCOS - FAQ & Feedback",
        "B-SSCOS - Log Masuk & Daftar": "B-SSCOS - Login & Register",
        "Koperasi Digital Bukharian": "Bukharian Digital Cooperative",
        "Sistem Koperasi Digital Sekolah": "School Digital Cooperative System",
        "Tempah barangan koperasi, semak stok, buat pembayaran dan pantau status pesanan melalui satu platform yang pantas, mudah dan teratur.": "Order cooperative items, check stock, make payments and track order status through one fast, simple and organised platform.",
        "Pesan Sekarang": "Order Now",
        "Terokai Sistem": "Explore the System",
        "Tempahan Teratur": "Organised Ordering",
        "Satu sistem, satu rekod": "One system, one record",
        "Akses Lebih Pantas": "Faster Access",
        "Semak dan pesan dalam talian": "Check and order online",
        "Pilihan Tingkatan": "Form Options",
        "Bayaran": "Payment",
        "Gabungan Semua Pesanan": "All Orders Combined",
        "Akses Sistem": "System Access",
        "Hari": "Days",
        "Penyediaan Pesanan": "Order Preparation",
        "Maklumat Penting Pesanan": "Important Order Information",
        "Semua pesanan yang disahkan akan disediakan dalam tempoh": "All confirmed orders will be prepared within",
        "2 hari bekerja": "2 working days",
        "selepas pembayaran berjaya disahkan.": "after payment has been successfully verified.",
        "Semua Dalam Satu Platform": "Everything on One Platform",
        "B-SSCOS membantu pelajar dan ibu bapa menempah barangan koperasi secara dalam talian, menyemak ketersediaan stok, membuat pembayaran QR, memuat naik resit dan memantau perkembangan pesanan dengan lebih tersusun.": "B-SSCOS helps students and parents order cooperative items online, check stock availability, make QR payments, upload receipts and track order progress in a more organised way.",
        "Pilih Barangan": "Choose Items",
        "Pilih barangan sekolah yang diperlukan.": "Choose the required school items.",
        "Pilih Kuantiti & Saiz": "Choose Quantity & Size",
        "Pilih kuantiti dan saiz bagi barangan yang berkaitan.": "Choose the quantity and size for applicable items.",
        "Pembayaran QR": "QR Payment",
        "Buat pembayaran dan muat naik resit.": "Make payment and upload the receipt.",
        "Ambil Barangan": "Collect Items",
        "Ambil barangan apabila status menjadi Sedia untuk Diambil.": "Collect the items when the status changes to Ready for Collection.",
        "Menyediakan platform digital yang cekap untuk perkhidmatan koperasi sekolah.": "Provide an efficient digital platform for school cooperative services.",
        "Memudahkan tempahan barangan sekolah dan meningkatkan pengurusan stok.": "Simplify school-item ordering and improve stock management.",
        "Mengurangkan masa menunggu serta memudahkan akses kepada maklumat produk dan stok.": "Reduce waiting time and improve access to product and stock information.",
        "Tempah barangan sekolah secara dalam talian.": "Order school items online.",
        "Semak ketersediaan stok mengikut saiz.": "Check stock availability by size.",
        "Dapatkan jawapan dan hantar aduan.": "Get answers and submit feedback.",
        "Lihat Soalan Lazim": "View FAQ",
        "Pilih tingkatan untuk melihat barangan set permulaan yang tersedia.": "Choose a form to view the available starter-set items.",
        "Lihat barangan set permulaan untuk pelajar Tingkatan 1.": "View starter-set items for Form 1 students.",
        "Lihat barangan set permulaan untuk pelajar Tingkatan 2.": "View starter-set items for Form 2 students.",
        "Lihat barangan set permulaan untuk pelajar Tingkatan 3.": "View starter-set items for Form 3 students.",
        "Lihat barangan set permulaan untuk pelajar Tingkatan 4.": "View starter-set items for Form 4 students.",
        "Lihat barangan set permulaan untuk pelajar Tingkatan 5.": "View starter-set items for Form 5 students.",
        "Lihat Barangan": "View Items",
        "1 Januari 2026": "1 January 2026",
        "3 Januari 2026": "3 January 2026",
        "5 Januari 2026": "5 January 2026",
        "Tempahan Dalam Talian Dibuka": "Online Ordering Is Open",
        "Tempahan dalam talian B-SSCOS kini dibuka.": "B-SSCOS online ordering is now open.",
        "Stok Baharu Pakaian Sukan": "New Sportswear Stock",
        "Stok bagi beberapa saiz pakaian sukan telah ditambah.": "Stock for several sportswear sizes has been replenished.",
        "Peringatan Pengambilan": "Collection Reminder",
        "Pesanan disediakan dalam tempoh dua hari bekerja selepas pembayaran disahkan.": "Orders are prepared within two working days after payment verification.",
        "B-SSCOS menjadikan urusan koperasi sekolah lebih lancar. Pelajar tidak perlu beratur lama dan urusan boleh dilakukan secara dalam talian dengan lebih cepat serta teratur.": "B-SSCOS makes school cooperative services smoother. Students no longer need to queue for long, and transactions can be completed online more quickly and systematically.",
        "En. Shamsul Badri": "Mr Shamsul Badri",
        "Saya boleh menyemak stok sebelum pergi ke sekolah.": "I can check stock before going to school.",
        "Ibu Bapa": "Parent",
        "Pesanan lebih mudah disediakan dan diuruskan.": "Orders are easier to prepare and manage.",
        "Guru Koperasi": "Cooperative Teacher",
        "Hubungi guru koperasi atau ikuti saluran rasmi sekolah untuk maklumat terkini.": "Contact the cooperative teacher or follow the school's official channels for the latest information.",
        "Puan Aida Narini": "Mrs Aida Narini",
        "Sistem Tempahan Koperasi Sekolah Bukharian": "Bukharian School Cooperative Ordering System",
        "Platform tempahan digital yang membantu pelajar dan ibu bapa membuat pesanan barangan koperasi, menyemak stok serta memantau status pesanan dengan lebih mudah dan teratur.": "A digital ordering platform that helps students and parents order cooperative items, check stock and track orders more easily and systematically.",
        "Semakan Stok": "Stock Check",
        "Perkhidmatan": "Services",
        "Tempahan Barangan": "Item Ordering",
        "Status Stok": "Stock Status",
        "Hantar Aduan": "Submit Feedback",
        "Hubungi Kami": "Contact Us",
        "E-mel": "Email",
        "Isnin – Jumaat": "Monday – Friday",
        "8:00 pagi – 4:00 petang": "8:00 AM – 4:00 PM",
        "© 2026 B-SSCOS. Hak cipta terpelihara.": "© 2026 B-SSCOS. All rights reserved.",

        "Bantuan Pengguna Dan Maklum Balas": "User Support and Feedback",
        "Cari jawapan kepada soalan umum, tapis maklumat mengikut kategori dan hantar aduan rasmi melalui Google Form.": "Find answers to common questions, filter information by category and submit official feedback.",
        "Cari Jawapan": "Find Answers",
        "Pusat Bantuan": "Help Centre",
        "Soalan lazim dan aduan pengguna": "Frequently asked questions and user feedback",
        "Semua": "All",
        "Pembayaran": "Payment",
        "Hubungan": "Contact",
        "Bagaimanakah cara membuat pesanan?": "How do I place an order?",
        "Pergi ke halaman Pesanan, pilih tingkatan dan barangan, tentukan kuantiti serta saiz, kemudian teruskan ke pembayaran.": "Go to the Order page, choose the form and items, set the quantities and sizes, then proceed to payment.",
        "Berapa lama pesanan akan disediakan?": "How long will an order take to prepare?",
        "Pesanan disediakan dalam tempoh 2 hari bekerja selepas pembayaran disahkan.": "Orders are prepared within 2 working days after payment verification.",
        "Bagaimanakah cara membuat pembayaran?": "How do I make a payment?",
        "Gunakan kod QR yang dipaparkan selepas membuat pesanan, kemudian muat naik resit pembayaran.": "Use the QR code shown after placing an order, then upload the payment receipt.",
        "Apakah yang perlu dilakukan jika resit ditolak?": "What should I do if my receipt is rejected?",
        "Muat naik resit baharu yang lebih jelas dan tunggu pengesahan pentadbir.": "Upload a clearer new receipt and wait for administrator verification.",
        "Bagaimanakah cara menyemak stok?": "How do I check stock?",
        "Buka halaman Stok untuk melihat stok semasa bagi setiap saiz pakaian.": "Open the Stock page to view current stock for each clothing size.",
        "Bagaimanakah cara menghubungi pentadbir koperasi?": "How do I contact the cooperative administrator?",
        "Gunakan butang WhatsApp atau maklumat hubungan pada Laman Utama.": "Use the WhatsApp button or the contact information on the Home page.",
        "Gunakan Google Form rasmi untuk menghantar aduan kepada pihak koperasi.": "Use the official feedback channel to send feedback to the cooperative.",
        "Buka Google Form": "Open Feedback Form",
        "Selepas aduan dihantar, pentadbir akan menyemak laporan dan menghantar jawapan ke alamat Gmail yang dimasukkan dalam Google Form.": "After feedback is submitted, the administrator will review it and respond through the email address provided.",
        "Pastikan alamat e-mel yang diberikan adalah tepat dan aktif.": "Make sure the email address provided is correct and active.",
        "Hubungi pentadbir koperasi melalui WhatsApp.": "Contact the cooperative administrator through WhatsApp.",

        "Akaun Pengguna Koperasi Digital": "Digital Cooperative User Account",
        "Log masuk ke akaun sedia ada atau daftar akaun baharu untuk membuat tempahan dan melihat sejarah pesanan anda.": "Log in to an existing account or register a new one to place orders and view your order history.",
        "Log Masuk Sekarang": "Login Now",
        "Log masuk dan daftar B-SSCOS": "Login and register for B-SSCOS",
        "Daftar": "Register",
        "Masukkan e-mel dan kata laluan yang telah didaftarkan.": "Enter your registered email and password.",
        "Belum mempunyai akaun?": "Do not have an account yet?",
        "Daftar akaun sebelum membuat pesanan pertama.": "Register an account before placing your first order.",
        "Minimum 6 aksara serta mesti mempunyai huruf besar, huruf kecil dan simbol.": "At least 6 characters with an uppercase letter, a lowercase letter and a symbol.",
        "Minimum 6 aksara, huruf besar, huruf kecil dan simbol.": "At least 6 characters, including uppercase, lowercase and a symbol.",
        "Sudah mempunyai akaun?": "Already have an account?",
        "Ini ialah prototaip bahagian hadapan. Akaun pengguna disimpan sementara dalam pelayar menggunakan localStorage.": "This is a frontend prototype. User accounts are temporarily stored in this browser using localStorage.",
        "Teruskan ke Pesanan": "Continue to Order",
        "6+ aksara": "6+ characters",
        "Huruf besar": "Uppercase",
        "Huruf kecil": "Lowercase",
        "Simbol": "Symbol",

        "Sistem Tempahan Koperasi Digital": "Digital Cooperative Ordering System",
        "Pilih semua tingkatan dan barangan yang diperlukan, kemudian gabungkan keseluruhannya dalam satu pembayaran yang mudah dan teratur.": "Choose all required forms and items, then combine them into one simple and organised payment.",
        "Pusat Pesanan": "Order Centre",
        "Pelbagai tingkatan, satu pembayaran": "Multiple forms, one payment",
        "Anda boleh memilih lebih daripada satu tingkatan dalam pesanan yang sama.": "You can choose more than one form in the same order.",
        "Pilih pakej rasmi Tingkatan 1 mengikut jantina.": "Choose the official Form 1 package by gender.",
        "Pakej rasmi Tingkatan 2 — jumlah penuh RM71.50.": "Official Form 2 package — full total RM71.50.",
        "Pakej rasmi Tingkatan 3 — jumlah penuh RM71.50.": "Official Form 3 package — full total RM71.50.",
        "Pakej rasmi Tingkatan 4 — jumlah penuh RM70.50.": "Official Form 4 package — full total RM70.50.",
        "Pakej rasmi Tingkatan 5 — jumlah penuh RM70.50.": "Official Form 5 package — full total RM70.50.",
        "Senarai adalah berdasarkan": "The list is based on the",
        "Senarai Keperluan Persekolahan Sesi 2026.": "2026 School Session Requirements List.",
        "Item yang mempunyai kuantiti dalam jadual ialah pakej wajib dan dikunci. Ruangan kosong ialah add-on pilihan pengguna.": "Items with quantities in the table form the required locked package. Blank quantity fields are optional add-ons.",
        "Pilih sekurang-kurangnya satu tingkatan di atas untuk melihat barangan yang tersedia.": "Choose at least one form above to view the available items.",
        "Pilih sekurang-kurangnya satu tingkatan di atas.": "Choose at least one form above.",
        "Draf pesanan disimpan automatik pada peranti ini.": "Your order draft is saved automatically on this device.",
        "Lihat pesanan terdahulu dan status semasa.": "View previous orders and their current status.",
        "Sila log masuk untuk melihat sejarah pesanan.": "Please log in to view your order history.",
        "Log Masuk Diperlukan": "Login Required",
        "Anda perlu log masuk sebelum melengkapkan pesanan.": "You need to log in before completing the order.",
        "Pembayaran Pesanan": "Order Payment",
        "Imbas kod QR DuitNow koperasi untuk membuat pembayaran.": "Scan the cooperative's DuitNow QR code to make payment.",
        "Ringkasan Pembayaran": "Payment Summary",
        "Nama:": "Name:",
        "E-mel:": "Email:",
        "Rujukan Pembayaran:": "Payment Reference:",
        "Format diterima: JPG, PNG atau PDF": "Accepted formats: JPG, PNG or PDF",
        "Muat Naik Resit & Sahkan Pesanan": "Upload Receipt & Confirm Order",
        "Ukuran ini ialah panduan. Pilih saiz yang paling sesuai sebelum membuat pembayaran.": "These measurements are a guide. Choose the most suitable size before making payment.",
        "Dipilih ✓": "Selected ✓",
        "Pakej wajib dan add-on berdasarkan jadual rasmi sesi 2026.": "Required package and add-ons based on the official 2026 schedule.",
        "Wajib — dipilih dan dikunci": "Required — selected and locked",
        "Add-on — pilihan pengguna": "Add-on — user choice",
        "Pilih Jantina Pelajar Tingkatan 1": "Choose the Gender of the Form 1 Student",
        "Tali Leher ialah item wajib bagi lelaki dan add-on pilihan bagi perempuan.": "A tie is required for male students and an optional add-on for female students.",
        "Lelaki — RM249.60": "Male — RM249.60",
        "Perempuan — RM229.60": "Female — RM229.60",
        "Sila pilih jantina untuk memaparkan pakej wajib dan add-on Tingkatan 1.": "Choose a gender to display the required package and add-ons for Form 1.",
        "Item bertanda": "Items marked",
        "tidak boleh dibuang dan kuantitinya dikunci.": "cannot be removed and their quantities are locked.",
        "tidak boleh dibuang dan kuantitinya dikunci. Item bertanda": "cannot be removed and their quantities are locked. Items marked",
        "Item bertanda": "Items marked",
        "hanya dimasukkan apabila pengguna menandakan checkbox.": "are included only when the user selects the checkbox.",
        "Bil.": "No.",
        "Perkara": "Item",
        "Tersedia": "Available",
        "Stok Rendah": "Low Stock",
        "Kuantiti wajib": "Required quantity",
        "Pilih 1 hingga 20": "Choose 1 to 20",
        "Pilihan": "Optional",
        "Dikunci": "Locked",
        "Buku": "Book",
        "Pakej wajib": "Required package",
        "Add-on dipilih": "Selected add-ons",
        "Tingkatan 1 — pilih jantina": "Form 1 — choose gender",
        "Sila pilih sekurang-kurangnya satu tingkatan.": "Please choose at least one form.",
        "Sila pilih jantina pelajar Tingkatan 1.": "Please choose the gender of the Form 1 student.",
        "Sila muat naik resit pembayaran.": "Please upload the payment receipt.",
        "Status Semasa": "Current Status",
        "Tiada sejarah pesanan ditemui.": "No order history found.",
        "Rujukan": "Reference",
        "Subtotal": "Subtotal",
        "Menunggu Pembayaran": "Pending Payment",
        "Pembayaran Sedang Disahkan": "Payment Under Verification",
        "Pembayaran Diluluskan": "Payment Approved",
        "Barangan Sedang Disediakan": "Preparing Items",
        "Sedia untuk Diambil": "Ready for Collection",
        "Selesai": "Completed",

        "Maklumat Stok Koperasi Semasa": "Current Cooperative Stock Information",
        "Semak baki pakaian sukan mengikut saiz, kenal pasti stok rendah dan lihat tarikh jangkaan stok semula sebelum membuat tempahan.": "Check sportswear balances by size, identify low stock and view expected restock dates before ordering.",
        "Semak Stok Sekarang": "Check Stock Now",
        "Pusat Stok": "Stock Centre",
        "Semakan baki mengikut saiz": "Balance check by size",
        "Amaran Stok Rendah:": "Low Stock Warning:",
        "Saiz yang mempunyai kurang daripada 5 unit akan ditandakan dengan warna merah.": "Sizes with fewer than 5 units are marked in red.",
        "Jangkaan Stok Semula:": "Expected Restock:",
        "10 Ogos 2026": "10 August 2026",
        "12 Ogos 2026": "12 August 2026",
        "Pelbagai pilihan saiz sedia ditempah.": "Various size options are ready to order.",
        "Pilihan warna rumah sukan dibuat semasa pesanan.": "The sports-house colour is chosen during ordering.",
        "Semua item daripada halaman Pesanan kecuali Saham Koperasi.": "All items from the Order page except Cooperative Shares.",
        "16 item": "16 items",
        "Buku Tulis A4": "A4 Exercise Book",
        "Buku Matematik": "Mathematics Book",
        "Buku Sumur (Edisi 2)": "SUMUR Book (Edition 2)",
        "Buku Catatan": "Notebook",
        "Wooven Beg": "Woven Bag",
        "Buku PAFA": "PAFA Book",
        "Buku Peraturan Sekolah": "School Regulations Book",
        "Buku Profil": "Profile Book",
        "Tali Leher": "Tie",
        "T-Shirt PJ": "PE T-Shirt",
        "T-Shirt Rasmi": "Official T-Shirt",
        "T-Shirt Rumah Sukan": "Sports House T-Shirt",
        "Seluar PJ": "PE Pants",
        "Lencana": "Badge",
        "Tanda Nama Digital (5 KPG)": "Digital Name Tag (5 PCS)",
        "Saham Koperasi": "Cooperative Shares",
        "Mengikut saiz": "By size",
        "Maklumat ini ialah paparan statik. Hubungi guru koperasi untuk pengesahan stok terkini atau pertukaran saiz.": "This is a static display. Contact the cooperative teacher to confirm current stock or request a size change.",

        "Sila lengkapkan semua ruangan.": "Please complete all fields.",
        "Kata laluan mestilah sekurang-kurangnya 6 aksara.": "The password must contain at least 6 characters.",
        "Kata laluan mesti mempunyai sekurang-kurangnya satu huruf besar.": "The password must contain at least one uppercase letter.",
        "Kata laluan mesti mempunyai sekurang-kurangnya satu huruf kecil.": "The password must contain at least one lowercase letter.",
        "Kata laluan mesti mempunyai sekurang-kurangnya satu simbol.": "The password must contain at least one symbol.",
        "Kata laluan dan pengesahan kata laluan tidak sepadan.": "The password and confirmation do not match.",
        "E-mel ini telah didaftarkan. Sila log masuk.": "This email is already registered. Please log in.",
        "Akaun berjaya didaftarkan. Sila log masuk menggunakan e-mel dan kata laluan anda.": "Account registered successfully. Please log in using your email and password.",
        "E-mel atau kata laluan tidak betul.": "The email or password is incorrect.",
        "Kata laluan mesti mempunyai minimum 6 aksara, huruf besar, huruf kecil dan simbol.": "The password must contain at least 6 characters, an uppercase letter, a lowercase letter and a symbol.",
        "Pengesahan kata laluan tidak sepadan.": "The password confirmation does not match.",
        "Kata laluan berjaya ditetapkan semula.": "The password was reset successfully."
    });

    const attributeTranslations = Object.assign({}, placeholderTranslations, {
        "Buka navigasi": "Open navigation",
        "Kembali ke atas": "Back to top",
        "Pelajar B-SSCOS": "B-SSCOS students",
        "Panduan saiz baju dan seluar sukan": "Sports shirt and pants size guide",
        "Tutup": "Close",
        "Buka troli": "Open cart",
        "Tutup troli": "Close cart",
        "Troli B-SSCOS": "B-SSCOS cart",
        "Pilihan bahasa": "Language selection",
        "Buka BukhariBot": "Open BukhariBot",
        "Tutup chatbot": "Close chatbot",
        "Soalan chatbot": "Chatbot question",
        "Hantar soalan": "Send question"
    });

    function readJSON(key, fallback) {
        try { return JSON.parse(localStorage.getItem(key) || "") || fallback; }
        catch (error) { return fallback; }
    }

    function money(value) { return "RM" + Number(value || 0).toFixed(2); }
    function text(ms, en) { return language === "en" ? en : ms; }

    const reverseTranslations = Object.keys(translations).reduce(function (result, malay) {
        if (!result[translations[malay]]) result[translations[malay]] = malay;
        return result;
    }, {});

    function translateDynamic(value) {
        const source = String(value == null ? "" : value).trim();
        if (!source) return source;
        if (translations[source]) return translations[source];

        let match = source.match(/^(\d+) unit$/i);
        if (match) return match[1] + " units";
        match = source.match(/^(\d+) set$/i);
        if (match) return match[1] + " sets";
        match = source.match(/^Tingkatan (\d+)(?: \((Lelaki|Perempuan)\))?$/i);
        if (match) return "Form " + match[1] + (match[2] ? " (" + (match[2].toLowerCase() === "lelaki" ? "Male" : "Female") + ")" : "");
        match = source.match(/^Tingkatan (\d+) — pilih jantina$/i);
        if (match) return "Form " + match[1] + " — choose gender";
        match = source.match(/^Panduan Saiz - (.+)$/i);
        if (match) return "Size Guide - " + translateDynamic(match[1]);
        match = source.match(/^Pakej wajib: (RM[\d.]+)$/i);
        if (match) return "Required package: " + match[1];
        match = source.match(/^(.+) Subjumlah:$/i);
        if (match) return translateDynamic(match[1]) + " Subtotal:";
        match = source.match(/^Rujukan: (.+)$/i);
        if (match) return "Reference: " + match[1];
        match = source.match(/^Draf pesanan disimpan automatik pada (.+)\.$/i);
        if (match) return "Order draft saved automatically at " + match[1] + ".";
        match = source.match(/^Anda telah log masuk sebagai (.+) \((.+)\)\.$/i);
        if (match) return "You are logged in as " + match[1] + " (" + match[2] + ").";
        match = source.match(/^(XS|S|M|L|XL|XXL|XXXL|XXXXL) - (Tersedia|Stok Rendah|Kehabisan Stok)$/i);
        if (match) return match[1] + " - " + translations[match[2]];
        return source;
    }

    function translateMessage(value) {
        let output = translateDynamic(value);
        if (output !== value) return output;
        const replacements = [
            ["Pesanan berjaya dihantar!", "Order submitted successfully!"],
            ["ID Pesanan:", "Order ID:"],
            ["Jumlah Pembayaran:", "Payment Total:"],
            ["Status: Pembayaran Sedang Disahkan", "Status: Payment Under Verification"],
            ["Item wajib tidak boleh dibuang:", "Required item cannot be removed:"],
            ["Sila masukkan kuantiti add-on yang sah untuk", "Please enter a valid add-on quantity for"],
            ["Sila pilih saiz untuk", "Please choose a size for"],
            [" dalam Tingkatan ", " in Form "],
            ["Pengguna", "User"]
        ];
        replacements.forEach(function (entry) { output = output.split(entry[0]).join(entry[1]); });
        Object.keys(translations).forEach(function (malay) {
            if (/^(Buku|T-Shirt|Seluar|Tali Leher|Lencana|Tanda Nama|Saham Koperasi|Wooven Beg|Sketch Pad)/.test(malay)) {
                output = output.split(malay).join(translations[malay]);
            }
        });
        return output;
    }

    function escapeHTML(value) {
        return String(value == null ? "" : value)
            .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;").replace(/'/g, "&#039;");
    }

    function buildLanguageSwitch() {
        const box = document.createElement("div");
        box.className = "bsscos-language-switch";
        box.setAttribute("aria-label", "Pilihan bahasa");
        box.innerHTML = '<button type="button" data-language="ms">BM</button><button type="button" data-language="en">EN</button>';
        box.addEventListener("click", function (event) {
            const button = event.target.closest("[data-language]");
            if (button) setLanguage(button.dataset.language);
        });
        document.body.appendChild(box);
        updateLanguageSwitch();
    }

    function updateLanguageSwitch() {
        document.querySelectorAll(".bsscos-language-switch [data-language]").forEach(function (button) {
            button.classList.toggle("is-active", button.dataset.language === language);
            button.setAttribute("aria-pressed", String(button.dataset.language === language));
        });
    }

    function translateTextNode(node) {
        const parent = node && node.parentElement;
        if (!parent || /^(SCRIPT|STYLE|NOSCRIPT|TEXTAREA)$/i.test(parent.tagName)) return;
        const rawValue = node.nodeValue;
        const current = rawValue.trim().replace(/\s+/g, " ");
        if (!current) return;

        if (!node.__bsscosMalay || (node.__bsscosLastRendered && current !== node.__bsscosLastRendered)) {
            if (translations[current] || translateDynamic(current) !== current) node.__bsscosMalay = current;
            else if (reverseTranslations[current]) node.__bsscosMalay = reverseTranslations[current];
            else node.__bsscosMalay = "";
        }

        if (!node.__bsscosMalay) return;
        const replacement = language === "en" ? translateDynamic(node.__bsscosMalay) : node.__bsscosMalay;
        if (replacement !== current) {
            const leading = (rawValue.match(/^\s*/) || [""])[0];
            const trailing = (rawValue.match(/\s*$/) || [""])[0];
            node.nodeValue = leading + replacement + trailing;
        }
        node.__bsscosLastRendered = replacement;
    }

    function translateAttributes(element) {
        if (!element || !element.getAttribute) return;
        ["placeholder", "aria-label", "title", "alt"].forEach(function (name) {
            const current = element.getAttribute(name);
            if (!current) return;
            element.__bsscosMalayAttributes = element.__bsscosMalayAttributes || {};
            const stored = element.__bsscosMalayAttributes[name];
            const last = element.__bsscosRenderedAttributes && element.__bsscosRenderedAttributes[name];
            if (!stored || (last && current !== last)) {
                if (attributeTranslations[current]) element.__bsscosMalayAttributes[name] = current;
                else if (reverseTranslations[current]) element.__bsscosMalayAttributes[name] = reverseTranslations[current];
            }
            const malay = element.__bsscosMalayAttributes[name];
            if (!malay) return;
            const rendered = language === "en" ? (attributeTranslations[malay] || translations[malay] || malay) : malay;
            element.setAttribute(name, rendered);
            element.__bsscosRenderedAttributes = element.__bsscosRenderedAttributes || {};
            element.__bsscosRenderedAttributes[name] = rendered;
        });
    }

    function translateTree(root) {
        if (!root || translating) return;
        translating = true;
        const nodes = [];
        if (root.nodeType === Node.TEXT_NODE) nodes.push(root);
        else {
            const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
            while (walker.nextNode()) nodes.push(walker.currentNode);
        }
        nodes.forEach(translateTextNode);

        if (root.nodeType === Node.ELEMENT_NODE) translateAttributes(root);
        if (root.querySelectorAll) root.querySelectorAll("[placeholder], [aria-label], [title], [alt]").forEach(translateAttributes);
        translating = false;
    }

    function setLanguage(next) {
        language = next === "en" ? "en" : "ms";
        localStorage.setItem(LANGUAGE_KEY, language);
        document.documentElement.lang = language === "en" ? "en" : "ms";
        updateLanguageSwitch();
        translateTree(document.body);
        if (!document.__bsscosMalayTitle) document.__bsscosMalayTitle = reverseTranslations[document.title] || document.title;
        document.title = language === "en" ? (translations[document.__bsscosMalayTitle] || document.__bsscosMalayTitle) : document.__bsscosMalayTitle;
        document.dispatchEvent(new CustomEvent("bsscos-language-change", { detail: { language: language } }));
    }

    function buildCart() {
        const toggle = document.createElement("button");
        toggle.className = "bsscos-cart-toggle";
        toggle.type = "button";
        toggle.setAttribute("aria-label", "Buka troli");
        toggle.innerHTML = '<i class="bi bi-cart3"></i><span class="bsscos-cart-count">0</span>';

        const backdrop = document.createElement("div");
        backdrop.className = "bsscos-cart-backdrop";

        const drawer = document.createElement("aside");
        drawer.className = "bsscos-cart-drawer";
        drawer.setAttribute("aria-label", "Troli B-SSCOS");
        drawer.innerHTML = `
            <header class="bsscos-cart-header">
                <div><h2><i class="bi bi-cart-check-fill me-2"></i><span data-cart-title></span></h2><small data-cart-subtitle></small></div>
                <button class="bsscos-cart-close" type="button" aria-label="Tutup troli"><i class="bi bi-x-lg"></i></button>
            </header>
            <div class="bsscos-cart-items"></div>
            <footer class="bsscos-cart-footer">
                <div class="bsscos-cart-total"><span data-cart-total-label></span><strong data-cart-total>RM0.00</strong></div>
                <div class="bsscos-cart-actions">
                    <button class="btn btn-outline-primary" type="button" data-cart-print><i class="bi bi-printer me-1"></i><span></span></button>
                    <button class="btn btn-outline-success" type="button" data-cart-download><i class="bi bi-download me-1"></i><span></span></button>
                    <a class="btn btn-primary wide" href="order.html"><i class="bi bi-bag-check me-1"></i><span data-cart-order></span></a>
                    <button class="btn btn-link text-danger wide" type="button" data-cart-clear></button>
                </div>
            </footer>`;

        document.body.append(toggle, backdrop, drawer);
        cartElements = { toggle: toggle, count: toggle.querySelector(".bsscos-cart-count"), backdrop: backdrop, drawer: drawer, items: drawer.querySelector(".bsscos-cart-items") };
        toggle.addEventListener("click", function () { openCart(true); });
        backdrop.addEventListener("click", function () { openCart(false); });
        drawer.querySelector(".bsscos-cart-close").addEventListener("click", function () { openCart(false); });
        drawer.querySelector("[data-cart-clear]").addEventListener("click", function () {
            if (cart.length && window.confirm(text("Kosongkan semua item dalam troli?", "Remove all items from the cart?"))) clearCart();
        });
        drawer.querySelector("[data-cart-print]").addEventListener("click", printSummary);
        drawer.querySelector("[data-cart-download]").addEventListener("click", downloadSummary);
        drawer.addEventListener("click", function (event) {
            const remove = event.target.closest("[data-cart-remove]");
            if (!remove) return;
            cart = cart.filter(function (item) { return item.key !== remove.dataset.cartRemove; });
            persistCart();
        });
        renderCart();
    }

    function openCart(open) {
        cartElements.drawer.classList.toggle("is-open", open);
        cartElements.backdrop.classList.toggle("is-open", open);
        document.body.style.overflow = open ? "hidden" : "";
        if (open) renderCart();
    }

    function normalizeItem(item, index) {
        const name = String(item.name || "Item");
        const size = String(item.size || "-");
        const form = String(item.form || "");
        return {
            key: String(item.key || [form, name, size, index].join("|")),
            name: name,
            price: Number(item.price || 0),
            qty: Math.max(1, Number(item.qty || 1)),
            size: size,
            form: form,
            type: String(item.type || "")
        };
    }

    function persistCart() {
        localStorage.setItem(CART_KEY, JSON.stringify(cart));
        renderCart();
        document.dispatchEvent(new CustomEvent("bsscos-cart-change", { detail: { items: cart.slice() } }));
    }

    function replaceCart(items) {
        cart = Array.isArray(items) ? items.map(normalizeItem) : [];
        persistCart();
    }

    function addToCart(item) {
        const normalized = normalizeItem(item, cart.length);
        const existing = cart.find(function (entry) { return entry.key === normalized.key; });
        if (existing) existing.qty += normalized.qty;
        else cart.push(normalized);
        persistCart();
        showToast(text("Item ditambah ke troli.", "Item added to cart."));
    }

    function clearCart() {
        cart = [];
        persistCart();
    }

    function cartTotal() {
        return cart.reduce(function (sum, item) { return sum + item.price * item.qty; }, 0);
    }

    function renderCart() {
        if (!cartElements) return;
        const count = cart.reduce(function (sum, item) { return sum + Number(item.qty || 0); }, 0);
        cartElements.count.textContent = count > 99 ? "99+" : String(count);
        cartElements.count.style.display = count ? "grid" : "none";
        cartElements.drawer.querySelector("[data-cart-title]").textContent = text("Troli Saya", "My Cart");
        cartElements.drawer.querySelector("[data-cart-subtitle]").textContent = text("Disimpan pada peranti ini", "Saved on this device");
        cartElements.drawer.querySelector("[data-cart-total-label]").textContent = text("Jumlah", "Total");
        cartElements.drawer.querySelector("[data-cart-total]").textContent = money(cartTotal());
        cartElements.drawer.querySelector("[data-cart-print] span").textContent = text("Cetak", "Print");
        cartElements.drawer.querySelector("[data-cart-download] span").textContent = text("Muat Turun", "Download");
        cartElements.drawer.querySelector("[data-cart-order]").textContent = text("Buka Halaman Pesanan", "Open Order Page");
        cartElements.drawer.querySelector("[data-cart-clear]").textContent = text("Kosongkan Troli", "Clear Cart");

        if (!cart.length) {
            cartElements.items.innerHTML = '<div class="bsscos-cart-empty"><i class="bi bi-cart-x"></i><strong>' + text("Troli masih kosong", "Your cart is empty") + '</strong><p>' + text("Pilih item di halaman Pesanan.", "Select items on the Order page.") + '</p></div>';
            return;
        }
        cartElements.items.innerHTML = cart.map(function (item) {
            const itemName = language === "en" ? translateDynamic(item.name) : item.name;
            const itemForm = language === "en" ? translateDynamic(item.form) : item.form;
            const itemType = language === "en" ? translateDynamic(item.type) : item.type;
            const details = [itemForm, itemType, item.size && item.size !== "-" ? text("Saiz ", "Size ") + item.size : ""].filter(Boolean).join(" • ");
            return '<article class="bsscos-cart-item"><div class="bsscos-cart-item-top"><div><strong>' + escapeHTML(itemName) + '</strong><small>' + escapeHTML(details) + '</small><small>' + text("Kuantiti", "Quantity") + ': ' + item.qty + '</small></div><button class="bsscos-cart-remove" type="button" data-cart-remove="' + escapeHTML(item.key) + '" aria-label="' + text("Buang item", "Remove item") + '"><i class="bi bi-trash3"></i></button></div><div class="bsscos-cart-item-price">' + money(item.price * item.qty) + '</div></article>';
        }).join("");
    }

    function summaryText() {
        const lines = ["B-SSCOS - " + text("Ringkasan Pesanan Sementara", "Temporary Order Summary"), "", text("Tarikh", "Date") + ": " + new Date().toLocaleString(language === "en" ? "en-MY" : "ms-MY"), ""];
        cart.forEach(function (item, index) {
            const itemName = language === "en" ? translateDynamic(item.name) : item.name;
            const itemForm = language === "en" ? translateDynamic(item.form) : item.form;
            const detail = [itemForm, item.size && item.size !== "-" ? text("Saiz", "Size") + ": " + item.size : ""].filter(Boolean).join(" | ");
            lines.push((index + 1) + ". " + itemName + " x " + item.qty + (detail ? " (" + detail + ")" : "") + " - " + money(item.price * item.qty));
        });
        lines.push("", text("Jumlah", "Total") + ": " + money(cartTotal()), "", text("Nota: Ini bukti sementara dan bukan resit pembayaran rasmi.", "Note: This is a temporary summary, not an official payment receipt."));
        return lines.join("\n");
    }

    function printSummary() {
        if (!cart.length) return showToast(text("Troli masih kosong.", "Your cart is empty."));
        const printWindow = window.open("", "_blank", "width=760,height=800");
        if (!printWindow) return showToast(text("Benarkan pop-up untuk mencetak.", "Allow pop-ups to print."));
        printWindow.document.write('<!doctype html><html><head><title>B-SSCOS</title><style>body{font-family:Arial,sans-serif;padding:34px;color:#172033}pre{white-space:pre-wrap;line-height:1.65}h1{color:#1d4ed8}</style></head><body><h1>B-SSCOS</h1><pre>' + escapeHTML(summaryText()) + '</pre></body></html>');
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
    }

    function downloadSummary() {
        if (!cart.length) return showToast(text("Troli masih kosong.", "Your cart is empty."));
        const blob = new Blob([summaryText()], { type: "text/plain;charset=utf-8" });
        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = "B-SSCOS_Ringkasan_Pesanan.txt";
        link.click();
        window.setTimeout(function () { URL.revokeObjectURL(link.href); }, 1000);
    }

    function showToast(message) {
        let toast = document.querySelector(".bsscos-toast");
        if (!toast) { toast = document.createElement("div"); toast.className = "bsscos-toast"; document.body.appendChild(toast); }
        toast.textContent = message;
        toast.classList.add("is-visible");
        window.clearTimeout(showToast.timer);
        showToast.timer = window.setTimeout(function () { toast.classList.remove("is-visible"); }, 1800);
    }

    function passwordIndicator(input) {
        if (!input || input.dataset.strengthReady) return;
        input.dataset.strengthReady = "true";
        const indicator = document.createElement("div");
        indicator.className = "bsscos-password-strength";
        indicator.innerHTML = '<div class="bsscos-password-meter"><span></span></div><ul class="bsscos-password-rules"><li data-rule="length"><i class="bi bi-circle me-1"></i><span>6+ aksara</span></li><li data-rule="upper"><i class="bi bi-circle me-1"></i><span>Huruf besar</span></li><li data-rule="lower"><i class="bi bi-circle me-1"></i><span>Huruf kecil</span></li><li data-rule="symbol"><i class="bi bi-circle me-1"></i><span>Simbol</span></li></ul>';
        (input.closest(".mb-3") || input.parentElement).appendChild(indicator);
        function update() {
            const value = input.value;
            const checks = { length: value.length >= 6, upper: /[A-Z]/.test(value), lower: /[a-z]/.test(value), symbol: /[^A-Za-z0-9]/.test(value) };
            const score = Object.values(checks).filter(Boolean).length;
            const bar = indicator.querySelector(".bsscos-password-meter span");
            bar.style.width = (score * 25) + "%";
            bar.style.background = score === 4 ? "#16a34a" : score >= 2 ? "#f59e0b" : "#dc2626";
            Object.keys(checks).forEach(function (key) {
                const row = indicator.querySelector('[data-rule="' + key + '"]');
                row.classList.toggle("is-valid", checks[key]);
                row.querySelector("i").className = "bi " + (checks[key] ? "bi-check-circle-fill" : "bi-circle") + " me-1";
            });
        }
        input.addEventListener("input", update);
        update();
    }

    function init() {
        buildLanguageSwitch();
        localStorage.removeItem("bsscosGlobalCartV1");
        passwordIndicator(document.getElementById("signupPassword"));
        passwordIndicator(document.getElementById("forgotNewPassword"));
        setLanguage(language);
        if (!window.__bsscosNativeAlert) {
            window.__bsscosNativeAlert = window.alert.bind(window);
            window.alert = function (message) {
                window.__bsscosNativeAlert(language === "en" ? translateMessage(String(message)) : message);
            };
        }
        const observer = new MutationObserver(function (mutations) {
            if (language !== "en" || translating) return;
            mutations.forEach(function (mutation) {
                if (mutation.type === "characterData") translateTree(mutation.target);
                mutation.addedNodes.forEach(function (node) {
                    if (node.nodeType === Node.ELEMENT_NODE || node.nodeType === Node.TEXT_NODE) translateTree(node);
                });
            });
        });
        observer.observe(document.body, { childList: true, characterData: true, subtree: true });
    }

    window.BSSCOSLanguage = {
        get: function () { return language; },
        set: setLanguage,
        translate: function (value) { return language === "en" ? translateDynamic(value) : value; },
        translateMessage: function (value) { return language === "en" ? translateMessage(value) : value; }
    };

    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
    else init();
})();
